# -*- coding: utf-8 -*-
"""Text Generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10hW_WFDpqzZnEBxj_41acUEvvyDd-wKq
"""

# NLP

!pip install transformers torch

from transformers import pipeline

# Load text generation model (GPT-2)
generator = pipeline(
    "text-generation",
    model="gpt2"
)

# Input
prompt = "Artificial Intelligence in finance will"

# Generate Text
result = generator(prompt, max_length=50, num_return_sequences=1)

print("AI Generated Text:")
print(result[0]["generated_text"])